sudo: false

language: node_js

node_js:
  - "6.0"
  - "8.0"

env:
  - global:
    - secure: "HkRiiONB4cs7t4+OEOjg6ZHdYeeMa1ZpqlvnRBBGSTnxWPQykd8dB88Upt5WvwRJdRcQZtHXhG63e7Lqynn7yZxZ2N7V2gNmv3APnfqnrQZ66Lr4H5vWoa6LFwRkgp3gTW1YWODZwMz08SnJKosSedISXyfzjFPDwNNuA9OO/Tg="

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

before_install:
  - npm install -g npm
  - npm install -g node-gyp
  - node-gyp clean

install:
  - export CXX=g++-4.8
  - $CXX --version
  - npm install

script:
  - NODE_ENV=test npm run coverage
  - NODE_ENV=test npm run lint

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
